# Generated by Django 3.2.25 on 2024-05-30 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articoli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=150, verbose_name='Titolo Articolo: ')),
                ('corpo', models.TextField()),
                ('data_pubblicatione', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
